apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: baf-authority-authority-trustee-auth-job
  annotations:
    flux.weave.works/automated: "false"
  namespace: baf-authority-ns
spec:
  releaseName: baf-authority-authority-trustee-auth-job
  chart:
    path: platforms/hyperledger-fabric/charts/indy-auth-job
    git: ssh://git@github.com/lyn-liu210/blockchain-automation-framework.git
    ref: local
  values:
    metadata:
      name: baf-authority-authority-trustee-auth-job
      namespace: baf-authority-ns
    network:
      name: baf
      kubernetes_url: https://10.0.1.4:8443
    image:
      name: baf-authority
      repository: alpine:3.9.4
    vault:
      address: http://13.71.136.104:80
      keyPath: baf-authority.trustees
      identity: authority-trustee
      admin_auth_path: kubernetes-baf-authority-admin-auth
      policy: baf-authority-authority-trustee-ro
      policy_content: path \"/baf-authority/trustees/authority-trustee/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-baf-authority-authority-trustee-auth
    account:
      admin_service: baf-authority-admin-vault-auth
      admin_role: rw
      service: baf-authority-authority-trustee-vault-auth
      role: ro
